"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 2, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]

[plugin]
prepend_previewers = [
    { name = "*.{md,json,jsonc,csv}", run = "bat" },
]

previewers = [
    { name = "*/", run = "folder", sync = true },
    { mime = "text/*", run = "bat" },
    { mime = "*/{xml,cs}", run = "bat" },
    { mime = "application/{mbox,javascript,wine-extension-ini}", run = "bat" },
]
