require("config.remap")
require("config.options")
require("custom.nvimcmds")
require("config.lazy")
require("config.lsp")
require("custom.statusline")
require("custom.tmuxnav")
require("custom.tmuxrun")
require("custom.tmuxbuild")

vim.cmd("colorscheme gruvbox-material")
ColorMyPencils()
