require("config.options")
require("config.remap")
require("config.pack")
require("config.lsp")
require("custom.autocmds")
require("custom.statusline")
require("custom.tmuxnav")

vim.cmd("colorscheme gruvbox-material")
ColorMyPencils()
