return {
    s("typst", {
        t({ "#set text(" }),
        t({ "", '    font: "Maple Mono NF",' }),
        t({ "", "    size: 16pt," }),
        t({ "", '    weight: "semibold",' }),
        t({ "", "    features: (" }),
        t({ "", '        "calt",' }),
        t({ "", '        "liga",' }),
        t({ "", '        // "ss01",' }),
        t({ "", '        // "ss02",' }),
        t({ "", '        "ss03",' }),
        t({ "", '        "ss04",' }),
        t({ "", '        "ss05",' }),
        t({ "", '        "ss06",' }),
        t({ "", '        "ss07",' }),
        t({ "", '        "ss08",' }),
        t({ "", '        "ss09",' }),
        t({ "", "    )," }),
        t({ "", ")" }),
        t({ "", "" }),
        t({ "", "#align(center)[#underline(text(" }),
        t({ "", '        weight: "bold",' }),
        t({ "", "        size: 24pt," }),
        t({ "", "        fill: blue," }),
        t({ "", "    )[" }),
        i(1, "Typst"),
        t({ "])" }),
        t({ "", "]" }),
    }),
}
