return {
    ---@diagnostic disable: undefined-global
    s("typst", {
        t({ "#set text(" }),
        t({ "", '    font: "Maple Mono NF",' }),
        t({ "", "    size: 16pt," }),
        t({ "", '    weight: "semibold",' }),
        t({ "", "    features: (" }),
        t({ "", '        "cv03",' }),
        t({ "", '        "cv09",' }),
        t({ "", '        "cv10",' }),
        t({ "", '        "cv42",' }),
        t({ "", '        "cv43",' }),
        t({ "", '        "cv66",' }),
        t({ "", '        "ss03",' }),
        t({ "", '        "ss07",' }),
        t({ "", '        "ss08",' }),
        t({ "", '        "ss09",' }),
        t({ "", '        "ss10",' }),
        t({ "", '        "ss11",' }),
        t({ "", '        "zero",' }),
        t({ "", "    )," }),
        t({ "", ")" }),
        t({ "", "" }),
        t({ "", "#align(center)[#underline(text(" }),
        t({ "", '        weight: "bold",' }),
        t({ "", "        size: 24pt," }),
        t({ "", "        fill: blue," }),
        t({ "", "    )[" }),
        i(1, "Typst"),
        t({ "])" }),
        t({ "", "]" }),
    }),
}
