#!/usr/bin/env bash

set -euo pipefail

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
CYAN='\033[1;36m'
NC='\033[0m'

if ! command -v yq &>/dev/null; then
    echo -e "${RED}Error: yq is not installed. Please install it first.${NC}"
    exit 1
fi

pkg_manager="yay -S --needed --noconfirm"
remove_manager="yay -Rns --noconfirm"
config_file="${DOTFILES:-$HOME/.dotfiles}/packages.toml"
lock_file="${DOTFILES:-$HOME/.dotfiles}/packages.lock"

# Initialize lock file if it doesn't exist
if [[ ! -f "$lock_file" ]]; then
    echo "{}" >"$lock_file"
fi

get_categories() {
    yq eval "keys | .[]" "$config_file" 2>/dev/null || true
}

get_packages() {
    yq eval ".${1}.packages // [] | .[]" "$config_file" 2>/dev/null || true
}

get_package_count() {
    yq eval ".${1}.packages // [] | length" "$config_file" 2>/dev/null || echo "0"
}

get_lock_packages() {
    yq eval ".${1}.packages // [] | .[]" "$lock_file" 2>/dev/null || true
}

update_lock_file() {
    # Read current state from config and update lock file
    local temp_lock=$(mktemp)
    echo "# This file is autogenerated." >"$temp_lock"
    echo "# This is not intended for manual editing." >>"$temp_lock"
    echo "# Last updated: $(date)." >>"$temp_lock"
    echo "" >>"$temp_lock"

    categories=$(get_categories)
    for category in $categories; do
        packages=$(get_packages "$category" | sort)
        # Convert packages array to TOML format using yq
        if [[ -n "$packages" ]]; then
            # Create category with packages array
            echo "$packages" | while IFS= read -r pkg; do
                yq eval -i ".${category}.packages += [\"$pkg\"]" "$temp_lock" 2>/dev/null
            done
        fi
    done

    # Replace old lock file
    mv "$temp_lock" "$lock_file"
}

package_status() {
    local to_install=()
    local to_remove=()
    local total_packages=0
    local already_installed=0

    categories=$(get_categories)

    for category in $categories; do
        # Get packages from config (desired state)
        config_packages=$(get_packages "$category" | sort)
        # Get packages from lock (previously installed state)
        lock_packages=$(get_lock_packages "$category" | sort)

        config_count=$(echo "$config_packages" | wc -w)
        lock_count=$(echo "$lock_packages" | wc -w)

        total_packages=$((total_packages + config_count))

        # Find packages to install (in config but not in lock)
        for pkg in $config_packages; do
            if ! echo "$lock_packages" | grep -q "^$pkg$"; then
                to_install+=("$pkg")
            fi
        done

        # Find packages to remove (in lock but not in config)
        for pkg in $lock_packages; do
            if ! echo "$config_packages" | grep -q "^$pkg$"; then
                to_remove+=("$pkg")
            fi
        done

        if [[ $config_count -gt 0 || $lock_count -gt 0 ]]; then
            echo -e "${CYAN}[$category]${NC}"

            # Show packages to remove (from lock)
            for pkg in $lock_packages; do
                if ! echo "$config_packages" | grep -q "^$pkg$"; then
                    echo -e "  ${RED}-${NC} $pkg"
                fi
            done

            # Show packages to install (from config)
            for pkg in $config_packages; do
                if ! echo "$lock_packages" | grep -q "^$pkg$"; then
                    echo -e "  ${BLUE}+${NC} $pkg"
                else
                    echo -e "  ${GREEN}✓${NC} $pkg"
                    already_installed=$((already_installed + 1))
                fi
            done

            echo
        fi
    done

    # Store in global variables
    TO_INSTALL=("${to_install[@]}")
    TO_REMOVE=("${to_remove[@]}")
    TOTAL_PACKAGES=$total_packages
    ALREADY_INSTALLED=$already_installed
}

install_packages() {
    if [[ ${#TO_INSTALL[@]} -eq 0 ]]; then
        echo -e "${YELLOW}|> No new packages to install${NC}"
        return 0
    fi

    echo -e "${BLUE}|> Installing ${#TO_INSTALL[@]} packages...${NC}"
    if $pkg_manager "${TO_INSTALL[@]}"; then
        echo -e "${GREEN}|> Installation completed${NC}\n"
    else
        echo -e "${RED}|> Installation failed${NC}\n"
        return 1
    fi
}

remove_packages() {
    if [[ ${#TO_REMOVE[@]} -eq 0 ]]; then
        echo -e "${YELLOW}|> No packages to remove${NC}"
        return 0
    fi

    echo -e "${YELLOW}|> Removing ${#TO_REMOVE[@]} packages...${NC}"
    echo -e "${YELLOW}The following packages will be removed:${NC}"
    printf "  %s\n" "${TO_REMOVE[@]}"

    read -p "Do you want to continue? [y/N]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}|> Skipping package removal${NC}"
        return 0
    fi

    if $remove_manager "${TO_REMOVE[@]}"; then
        echo -e "${GREEN}|> Removal completed${NC}\n"
    else
        echo -e "${RED}|> Removal failed${NC}\n"
        return 1
    fi
}

summary() {
    echo -e "${BLUE}|> Summary${NC}"
    echo -e "  ${CYAN}-> Total packages: $TOTAL_PACKAGES${NC}"
    echo -e "  ${YELLOW}-> Already installed: $ALREADY_INSTALLED${NC}"
    echo -e "  ${GREEN}-> Newly installed: ${#TO_INSTALL[@]}${NC}"
    echo -e "  ${RED}-> Removed: ${#TO_REMOVE[@]}${NC}"

    if [[ ${#TO_INSTALL[@]} -gt 0 || ${#TO_REMOVE[@]} -gt 0 ]]; then
        echo -e "\n${BLUE}|> Updating lock file...${NC}"
        if update_lock_file; then
            echo -e "${GREEN}|> Lock file updated${NC}"
        else
            echo -e "${RED}|> Failed to update lock file${NC}"
        fi
    fi
}

main() {
    package_status

    if [[ ${#TO_INSTALL[@]} -eq 0 && ${#TO_REMOVE[@]} -eq 0 ]]; then
        echo -e "${GREEN}|> Packages are already synchronized${NC}"
        summary
        return 0
    fi

    install_packages && remove_packages && summary
}

main "$@"
