name: Build fonts

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Clone src repository
        run: git clone https://github.com/subframe7536/maple-font --depth 1 -b variable
      - name: Install dependencies
        run: |
          cd maple-font
          pip install -r requirements.txt
      - name: Build Maple font
        run: |
          cd maple-font
          chmod +x build.py
          ./build.py --format otf,woff2 --feat cv03,cv09,cv10,cv42,cv43,cv66,ss07,ss08,ss09,ss10,ss11,zero --nf --nf-variable --liga --apply-fea-file --remove-tag-liga --infinite-arrow --archive
      - name: Add fonts to release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd maple-font/fonts/archive
          install="MapleMono-NF-VF.zip MapleMono-Woff2.zip MapleMono-OTF.zip"
          gh release delete "Fonts" --repo ${{ github.repository }} --yes 2>/dev/null || true
          gh release create "Fonts" $install --repo ${{ github.repository }} --title "Maple Mono NF" --notes-file ../../../.github/fonts.md
